<?php

namespace Database\Seeders;

use App\Models\DiseaseType;
use Illuminate\Database\Seeder;

class DiseaseTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if data already exists
        if (DiseaseType::exists()) return;

        // List of disease types
        $diseases = [
            ['name' => 'Coronavirus (COVID-19)'],
            ['name' => 'Tuberculosis (TB)'],
            ['name' => 'Meningitis'],
            ['name' => 'HIV/AIDS'],
            ['name' => 'Malaria'],
            ['name' => 'Ebola'],
            ['name' => 'Down Syndrome'],
            ['name' => 'Cystic Fibrosis'],
            ['name' => 'Hemophilia'],
            ['name' => 'Sickle Cell Anemia'],
            ['name' => 'Huntington’s Disease'],
            ['name' => 'Rheumatoid Arthritis'],
            ['name' => 'Lupus'],
            ['name' => 'Colitis'],
            ['name' => 'Multiple Sclerosis'],
            ['name' => 'Typhoid Fever'],
            ['name' => 'Diabetes'],
            ['name' => 'Phenylketonuria'],
            ['name' => 'Gout'],
            ['name' => 'Hormonal Disorders'],
            ['name' => 'Alzheimer’s Disease'],
            ['name' => 'Parkinson’s Disease'],
            ['name' => 'Epilepsy'],
            ['name' => 'Hypertension'],
            ['name' => 'Heart Disease'],
            ['name' => 'Stroke'],
            ['name' => 'Chronic Respiratory Disease'],
            ['name' => 'Asthma'],
            ['name' => 'COPD (Chronic Obstructive Pulmonary Disease)'],
            ['name' => 'Pneumonia'],
            ['name' => 'Lung Cancer'],
            ['name' => 'Thyroid Disorders'],
            ['name' => 'Cushing’s Syndrome'],
            ['name' => 'Addison’s Disease'],
            ['name' => 'Breast Cancer'],
            ['name' => 'Skin Cancer'],
            ['name' => 'Leukemia'],
            ['name' => 'Depression'],
            ['name' => 'Anxiety Disorder'],
            ['name' => 'Bipolar Disorder'],
            ['name' => 'Schizophrenia'],
            ['name' => 'Chronic Kidney Disease'],
            ['name' => 'Liver Disease'],
            ['name' => 'Pancreatitis'],
            ['name' => 'Gastritis'],
            ['name' => 'Hepatitis'],
            ['name' => 'Obesity'],
            ['name' => 'Celiac Disease'],
            ['name' => 'Psoriasis'],
            ['name' => 'Migraine'],
            ['name' => 'Osteoporosis'],
            ['name' => 'Glaucoma'],
            ['name' => 'Cataract'],
            ['name' => 'Autism Spectrum Disorder'],
            ['name' => 'Dementia'],
            ['name' => 'Anemia'],
            ['name' => 'Hypothyroidism'],
            ['name' => 'Hyperthyroidism'],
            ['name' => 'Hemorrhoids'],
            ['name' => 'Varicose Veins'],
            ['name' => 'Hepatitis B'],
            ['name' => 'Hepatitis C'],
            ['name' => 'Cholera'],
            ['name' => 'Diphtheria'],
            ['name' => 'Rabies'],
            ['name' => 'Tetanus'],
            ['name' => 'Yellow Fever'],
            ['name' => 'Polio'],
            ['name' => 'Leprosy'],
            ['name' => 'Lyme Disease'],
            ['name' => 'Zika Virus'],
            ['name' => 'Dengue Fever'],
            ['name' => 'Chikungunya'],
            ['name' => 'Norovirus'],
            ['name' => 'Rotavirus'],
            ['name' => 'Salmonella Infection'],
            ['name' => 'Shigella Infection'],
            ['name' => 'Anthrax'],
            ['name' => 'Botulism'],
            ['name' => 'Brucellosis'],
            ['name' => 'Plague'],
            ['name' => 'Rocky Mountain Spotted Fever'],
            ['name' => 'West Nile Virus'],
            ['name' => 'Filariasis'],
            ['name' => 'Trichomoniasis'],
            ['name' => 'Syphilis'],
            ['name' => 'Gonorrhea'],
            ['name' => 'Chlamydia'],
            ['name' => 'HPV Infection'],
            ['name' => 'Herpes Simplex Virus'],
            ['name' => 'Mononucleosis'],
            ['name' => 'Measles'],
            ['name' => 'Mumps'],
            ['name' => 'Rubella'],
            ['name' => 'Chickenpox'],
            ['name' => 'Shingles'],
            ['name' => 'Toxoplasmosis'],
            ['name' => 'Giardiasis'],
            ['name' => 'Cryptosporidiosis'],
            ['name' => 'Leishmaniasis'],
            ['name' => 'Trypanosomiasis'],
            ['name' => 'Schistosomiasis'],
            ['name' => 'Tapeworm Infection'],
            ['name' => 'Ascariasis'],
            ['name' => 'Hookworm Infection'],
            ['name' => 'Trichinosis'],
            ['name' => 'Lupus Nephritis'],
            ['name' => 'Fibromyalgia'],
            ['name' => 'Cervical Cancer'],
            ['name' => 'Ovarian Cancer'],
            ['name' => 'Prostate Cancer'],
            ['name' => 'Colon Cancer'],
            ['name' => 'Brain Tumor'],
            ['name' => 'Esophageal Cancer'],
            ['name' => 'Bladder Cancer'],
            ['name' => 'Pancreatic Cancer']
        ];

        // Insert into the database
        DiseaseType::insert($diseases);
    }
}
